### ISSUE TITLE
Bug!?

### ISSUE THREAD

**Issue by Pub4Game** [PurePlugins/PurePerms#146]
I use MySQL....

![image](https://cloud.githubusercontent.com/assets/11244874/11077664/568c5c30-8812-11e5-9cf4-842fa760b3b1.png)

![image](https://cloud.githubusercontent.com/assets/11244874/11077674/5e2cead6-8812-11e5-8d70-1bf403cb6ee9.png)

Whay???

groups.yml

```
---
Guest:
  isDefault: true
  inheritance: []
  permissions:
  - -essentials.kit
  - -essentials.kit.other
  - -pocketmine.command.me
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pperms.command.ppinfo
  worlds: []
Admin:
  inheritance:
  - Guest
  permissions:
  - essentials.gamemode
  - pocketmine.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - pocketmine.command.time
  worlds: []
Owner:
  inheritance:
  - Guest
  - Admin
  permissions:
  - essentials
  - pocketmine.command
  - pperms.command
  worlds: []
OP:
  inheritance: []
  permissions:
  - '*'
  worlds: []
...

```

![image](https://cloud.githubusercontent.com/assets/11244874/11077707/85123070-8812-11e5-8ac7-7b6840859228.png)
