### ISSUE TITLE
MySQL is really buggy

### ISSUE THREAD

**Issue by SURVAml** [PurePlugins/PurePerms#207]
Hi,
I'm trying to use MySQL with PurePerms for multiple servers.
My config:
```
---
data-provider: mysql
default-language: de
disable-op: true
enable-multiworld-perms: false
enable-noeul-sixtyfour: false
mysql-settings:
  host: ***
  port: 3306
  user: ***
  password: ***
  db: ***
noeul-minimum-pw-length: 6
superadmin-ranks:
- OP
...

```

When I start the server, it creates the mysql tables and the groups.yml and players.yml in the config folder. Now, when I restart the server like it is, it creates the mysql tables again. Here's a screenshot after some restarts:

![ohne titel](https://cloud.githubusercontent.com/assets/15860314/13526914/7a7e4060-e20b-11e5-8b1f-4c210c041c20.jpg)

When I stop the server, delete the groups.yml and then start it, the bug is not there.
