### ISSUE TITLE
YAMLv1 provider doesn't work well.

### ISSUE THREAD

**Issue by AryToNeX** [PurePlugins/PurePerms#214]
I am using YAMLv1 but the plugin always listens to players/ folder instead of players.yml file.

Switched to 1.3.0_01 for now.

**Comment by jazzwhistle** [comment]
Did you set the provider to "yamlv1" without the quotes? Can you paste your config.yml?

**Comment by AryToNeX** [comment]
```
---
data-provider: "yamlv2" # also tried with yamlv2 without quotes
default-language: en
enable-multiworld-perms: false
msg-on-group-change: Now you are in group {group}!
disable-op: true
enable-noeul-sixtyfour: false
mysql-settings:
  host: PurePerms-FTW.loveyou.all
  port: 3306
  user: YourUsernameGoesHere
  password: YourPasswordGoesHere
  db: YourDBNameGoesHere
noeul-minimum-pw-length: 6
superadmin-ranks:
- Owner
...

```
and it still does not work. @64FF00
