### ISSUE TITLE
MultiWorld Perms don't work

### ISSUE THREAD

**Issue by winterbuild7074** [PurePlugins/PurePerms#265]
I turned on MultiWorld Perms, and I noticed that none of the permissions are working anymore.

```
VIP:
  alias: vip
  isDefault: false
  inheritance: []
  permissions:
  - -essentials.kit
  - -essentials.kit.other
  - -myplot.command.generate
  - -pocketmine.command.me
  - -pocketmine.command.version
  - -pperms.command.ppinfo
  - chattoolspro.tipgive
  - cratekeys.use
  - essentials.back
  - essentials.compass
  - essentials.depth
  - essentials.extinguish
  - essentials.feed
  - essentials.getpos
  - essentials.heal
  - essentials.near
  - essentials.ptime.use
  - essentials.seen
  - essentials.sign.color
  - essentials.sign.use.warp
  - essentials.vanish.pvp
  - essentials.vanish.use
  - essentials.warps.*
  - itemblocker.chest
  - itemblocker.drop
  - itemblocker.place
  - myplot.claimplots.5
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.enchant
  - pocketmine.command.list
  - pocketmine.command.teleport
  worlds:
    Farming:
      isDefault: false
      permissions: []
    Spawn:
      isDefault: false
      permissions:
      - essentials.sign.use.warp
      - essentials.warps.*
    Games:
      isDefault: false
      permissions: []
    Plots:
      isDefault: false
      permissions:
      - essentials.fly.use
    Roleplay:
      isDefault: false
      permissions: []
    Shop:
      isDefault: false
      permissions: []
    Shopp:
      isDefault: false
      permissions: []
    SkyWars:
      isDefault: false
      permissions: []
    SkyWars-2:
      isDefault: false
      permissions: []
    Parkour-Extreme:
      isDefault: false
      permissions: []
    Mazes:
      isDefault: false
      permissions: []
    nether:
      isDefault: false
      permissions: []
    PvP1:
      isDefault: false
      permissions: []
    Contest-Plots:
      isDefault: false
      permissions:
      - essentials.fly.use
```
PasteBin: https://pastebin.com/tG7jU9bA

The permissions on top like `essentials.warps.*` aren't working. I also tried adding `essentials.fly.use` to my Plots World, but they don't work too.
All the permissions were working before, but after turning on MultiWorld Perms, I'm getting problems.

What am I doing wrong? Or maybe I need to update it? I think I'm using PurePerms from February or March 2017.
