### ISSUE TITLE
Multiworld doesn't work

### ISSUE THREAD

**Issue by isoz** [PurePlugins/PurePerms#294]
I noticed a few old commits stating to have fixed MultiWorld but it doesn't work.

enable-multiworld-perms is set to true

Examples groups:
```
God:
  isDefault: false
  alias: god
  inheritance:
  - Guest
  permissions:
  - essentials.back.ondeath
  - essentials.ptime.use
  - essentials.repair.use
  worlds:
    plots:
      isDefault: false
      permissions:
      - pocketmine.command.teleport
```

Using yamlv2 as provider, no errors.
PurePerms_dev-14
