### ISSUE TITLE
Plugin PurePerms is disabled - ppreload

### ISSUE THREAD

**Issue by dallinac** [PurePlugins/PurePerms#39]
PurePerms is not working for me. When I made a change in the groups file since for some reason warps weren't working, even though I'm an op it gave me this error:
```
[14:55:04] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[14:55:04] [Server thread/CRITICAL]: Unhandled exception executing command 'ppreload' in ppreload: Plugin PurePerms is disabled
[14:55:04] [Server thread/CRITICAL]: pocketmine\utils\PluginException: "Plugin PurePerms is disabled" (EXCEPTION) in "/src/pocketmine/permission/PermissibleBase" at line 133
```
My groups.yml is valid YAML, but here it is for reference:
```
---
Guest:
  isDefault: true
  inheritance: []
  permissions:
  - essentials.sign.use
  - essentials.afk
  - essentials.back
  - essentials.compass
  - essentials.getpos
  - essentials.home
  - essentials.sethome
  - essentials.delhome
  - essentials.suicide
  - essentials.spawn
  - essentials.tpa
  - essentials.tpaccept
  - essentials.tpdeny
  - essentials.warp
  - essemtials.warps
  - essentials.warps.*
  - essentials.world
  - -pocketmine.command.me
  - pocketmine.command.help
  - pocketmine.command.list
  - pperms.command.ppinfo
  - economyusury.command.usury
  - - economyusury.command.usury.host
  - economyapi.*
  - - economyapi.command.setmoney
  - - economyapi.command.givemoney
  - - economyapi.command.seemoney
  - - economyapi.command.takemoney
  - - essentials.sign.create
  - - essentials.sign.use.gamemode
  - - essentials.sign.use.time
  - - essentials.sign.break
  worlds: []
Admin:
  inheritance:
  - Guest
  permissions:
  - essentials.gamemode
  - essentials.broadcast
  - pocketmine.command.gamemode
  - pocketmine.command.give
  - pocketmine.command.kick
  - pocketmine.command.teleport
  - economyusury.*
  worlds: []
SuperAdmin:
  inheritance:
  - Guest
  - Admin
  - essentials.burn
  - essentials.extinguish
  - essentials.heal
  - essentials.item
  - essentials.kill
  - essentials.more
  - essentials.near
  - essentials.sign.break
  - essentials.sign.use
  - essentials.sign.create
  - essentials.repair
  - essentials.repair.armor
  - essentials.tempban
  - essentials.setwarp
  - essentials.delwarp
  - economyshop.*
  - economysell.*
  - economyairport.*
OP:
  inheritance: []
  permissions:
  - '*'
  worlds: []
...
```
