### ISSUE TITLE
Denying permissions

### ISSUE THREAD

**Issue by AryToNeX** [PurePlugins/PurePerms#70]
Hi! I setted in my groups.yml:
```
User:
  isDefault: true
  inheritance: []
  permissions:
  - -myplot.command.biome
  - -walkingparticles
  - -walkingparticles.command
  - myplot.command.claim
  worlds: []
VIP:
  isDefault: true
  inheritance:
  - User
  permissions:
  - myplot.command.biome
  - armorspawn.receive
  - walkingparticles
  - walkingparticles.command
  worlds: []
```

But VIPs don't have permission to do /p biome and /wparticles and armor is gived to all players! What I'm doing wrong? Is it a bug?
